name: Download and Commit Kick Video

on:
  workflow_dispatch:

permissions:
  contents: write  # ✅ Required to push to the repository

jobs:
  download:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ensure videos folder exists
        run: mkdir -p videos

      - name: Build Docker image
        run: docker build -t kick-video-downloader .

      - name: Run container to download video into repo folder
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/videos:/app/videos \
            kick-video-downloader

      - name: Show downloaded video file
        run: ls -lh videos

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push video to repo
        run: |
          if git status --porcelain | grep 'videos/'; then
            git add videos/kick_video.mp4
            git commit -m "Add downloaded Kick video"
            git push
          else
            echo "⚠️ No changes to commit."
          fi
